replicaCount: 1
updateType: RollingUpdate
host: arch.homework
context_path_template: /otusapp/alex($|/)(.*)
nameOverride: app-chart
#otusapp/alex
image: aystream/health:v2.7 # todo обновить image и тут поменять

service:
  type: NodePort
  internalPort: 8000
  externalPort: 8000
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 5
  readiness:
    path: /health
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 2
    successThreshold: 1
    failureThreshold: 5

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: app_test
  service:
    port: "5432"

 # helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx/
 # helm repo update && helm install nginx stable/nginx-ingress --namespace monitoring -f nginx-ingress.yaml && minikube ip