apiVersion: v2
name: app-chart
description: A Helm chart for Kubernetes

type: application

version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: prometheus-operator
    version: 9.x.x
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: nginx-ingress
    version: 1.41.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: prometheus-postgres-exporter
    version: 1.3.0
    repository: https://kubernetes-charts.storage.googleapis.com